[package]
name = "torchc_hike"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
async-walkdir = "1.0.0"
torchc_lits = { path = "../torchc_lits" }
torchc_script = { path = "../torchc_script" }
colored = "2.1.0"
