[package]
name = "torchc_diagnosis"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
async-std = "1.12.0"
torchc_script = { path = "../torchc_script" }
torchc_lex = { path = "../torchc_lex" }
torchc_lits = { path = "../torchc_lits" }
pathdiff = "0.2.1"
